//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AKSAM_LISTESI
{
    public int ID { get; set; }
    public string YIYECEK_ADI { get; set; }
    public Nullable<int> KALORI_MIKTARI { get; set; }
    public Nullable<int> GRAM { get; set; }
}

public partial class ARA_OGUNLER
{
    public int ID { get; set; }
    public string YIYECEK_ADI { get; set; }
    public Nullable<int> KALORI_MIKTARI { get; set; }
    public Nullable<int> GRAM { get; set; }
}

public partial class KULLANICI_LISTESI
{
    public int ID { get; set; }
    public string KULLANICIADI { get; set; }
    public string SIFRE { get; set; }
    public Nullable<bool> YETKILIMI { get; set; }
}

public partial class MESAJLAR_LISTESI
{
    public int ID { get; set; }
    public string ADISOYADI { get; set; }
    public string EPOSTA { get; set; }
    public string KONU { get; set; }
    public string MESAJ { get; set; }
}

public partial class OGLE_LISTESI
{
    public int ID { get; set; }
    public string YIYECEK_ADI { get; set; }
    public Nullable<int> KALORI_MIKTARI { get; set; }
    public Nullable<int> GRAM { get; set; }
}

public partial class SABAH_LISTESI
{
    public int ID { get; set; }
    public string YIYECEK_ADI { get; set; }
    public Nullable<int> KALORI_MIKTARI { get; set; }
    public Nullable<int> GRAM { get; set; }
}
