//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AKSAM_LISTESI
{
    public int ID { get; set; }
    public string YIYECEK_ADI { get; set; }
    public Nullable<int> KALORI_MIKTARI { get; set; }
    public Nullable<int> GRAM { get; set; }
}

public partial class ARA_OGUNLER
{
    public int ID { get; set; }
    public string YIYECEK_ADI { get; set; }
    public Nullable<int> KALORI_MIKTARI { get; set; }
    public Nullable<int> GRAM { get; set; }
}

public partial class OGLE_LISTESI
{
    public int ID { get; set; }
    public string YIYECEK_ADI { get; set; }
    public Nullable<int> KALORI_MIKTARI { get; set; }
    public Nullable<int> GRAM { get; set; }
}

public partial class SABAH_LISTESI
{
    public int ID { get; set; }
    public string YIYECEK_ADI { get; set; }
    public Nullable<int> KALORI_MIKTARI { get; set; }
    public Nullable<int> GRAM { get; set; }
}

public partial class sysdiagrams
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}
