//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class veritabani : DbContext
{
    public veritabani()
        : base("name=veritabani")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<AKSAM_LISTESI> AKSAM_LISTESI { get; set; }
    public virtual DbSet<ARA_OGUNLER> ARA_OGUNLER { get; set; }
    public virtual DbSet<OGLE_LISTESI> OGLE_LISTESI { get; set; }
    public virtual DbSet<SABAH_LISTESI> SABAH_LISTESI { get; set; }
    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
}
